### ISSUE TITLE
Include Config from Other Files

### ISSUE THREAD

**Issue by vst** [vst/opsops#29]
As number of secrets increase, it becomes difficult to *see* and *manage* them in a single YAML file.

Something like:

```yaml
services:
  api:
    token:
      type: "op-read"
      value:
        account: "IPAEPH0JI3REE8FICHOOVU4CHA"
        uri: "op://Devops/OokahCuZ4fo8ahphie1aiFa0ei/API Tokens/write-only"
  customer1:
    include: ./customer1.yaml
  customer2:
    include: ../customer2/opsops.yaml
  customer3:
    include: /data/customer3/config/opsops.yaml
```

Another option was to switch to TOML as it reads better, but I want to stick to JSON/YAML as tooling is more ubiquitous.
